# This is a basic workflow to help you get started with Actions

name: Production workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Development Codes
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
          
      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: yarn install
        
      # Runs a single command using the runners shell
#       - name: Test UI
#         run: yarn run test
        
      # Runs a single command using the runners shell
      - name: Build Production
        run: yarn run build --if-present
        
      # Runs a single command using the runners shell
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'didapatria-challenge-client'
          heroku_email: 'didapatria3@gmail.com'
